version: "3.8"

name: "disk-and-memory-usage"

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: disk_memory_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
  web:
    build: .
    environment:
      SQLALCHEMY_DATABASE_URL: "mysql+pymysql://user:password@db/disk_memory_db"
    volumes:
      - .:/app
      - /:/host/root:ro
      - /proc:/host/proc:ro
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
