version: "3.8"

name: "disk-and-memory-usage"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
  web:
    build: .
    container_name: "disk-and-memory-usage-monitor"
    environment:
      SQLALCHEMY_DATABASE_URL: "mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db/${MYSQL_DB}"
    volumes:
      - /:/host/root:ro
      - /proc:/host/proc:ro
    ports:
      - "${WEB_PORT}:8000"
    depends_on:
      - db
    networks:
      - app-network
      - proxy 

networks:
  app-network:
    driver: bridge
  proxy:
    name: "reverse-proxy"
    external: true

volumes:
  db_data:
